{{cookiecutter.project_name}}:
  ros__parameters:
    # The maximum rate at which updates should occur, and hence the max rate at which commands are sent.
    # Leaving this unset makes the max update rate unlimited.
    # update_rate: 50.0

    # The minimum rate at which updates occur.
    # Leaving this unset will allow for indefinite lapses between updates.
    min_update_rate: 2.0

    input_sources:
      names: [
        "game_controller_source"
      ]

      # Declare types for the sources
      game_controller_source:
        type: "teleop_modular_joy/JoyInputSource"

    control_modes:
      names: [
        "normal_mode",
        "turbo_mode"
      ]

      # Declare types for the modes
      normal_mode:
        type: "joint_space_control_mode/JointSpaceControlMode"
      turbo_mode:
        type: "teleop_modular_twist/TwistControlMode"

    commands:
      names: [
        "enter_turbo_mode",
        "enter_normal_mode"
      ]

      enter_turbo_mode:
        on: "turbo_mode/down"
        type: "activate_control_mode"
        name: "turbo_mode"
      enter_normal_mode:
        on: "turbo_mode/up"
        type: "activate_control_mode"
        name: "normal_mode"


game_controller_source:
  ros__parameters:
    topic: "/joy"
    # These are the default mappings for a game_controller_node.
    # https://docs.ros.org/en/ros2_packages/rolling/api/joy/index.html
    # If you use joy_node, you'll need to figure out what the mapping is yourself.
    # So, run joy, `ros2 topic echo /joy`, and mess around with your controller to figure out what it is for you.
    button_definitions: [
      "A",
      "B",
      "X",
      "Y",
      "BACK",
      "GUIDE",
      "START",
      "LEFTSTICK",
      "RIGHTSTICK",
      "LEFTSHOULDER",
      "RIGHTSHOULDER",
      "DPAD_UP",
      "DPAD_DOWN",
      "DPAD_LEFT",
      "DPAD_RIGHT",
      "MISC1",
      "PADDLE1",
      "PADDLE2",
      "PADDLE3",
      "PADDLE4",
      "TOUCHPAD"
    ]
    axis_definitions: [
      "LEFTX",
      "LEFTY",
      "RIGHTX",
      "RIGHTY",
      "TRIGGERLEFT",
      "TRIGGERRIGHT"
    ]

    remap:
      axes:
        linear:
          x:
            from: "LEFTX"
          y:
            from: "LEFTY"
        angular:
          z:
            from: "RIGHTX"

      buttons:
        turbo_mode:
          from: "RIGHTSHOULDER"


normal_mode:
  ros__parameters:
    topic: "/turtle1/cmd_vel"
    use_speed_input: false

    scale:
      linear:
        x: 1.0
      angular:
        z: 1.0


turbo_mode:
  ros__parameters:
    topic: "/turtle1/cmd_vel"
    use_speed_input: false

    scale:
      linear:
        x: 4.0
      angular:
        z: 4.0

